BUG FIX due to HUGO or formatting problem
Error: Error building site: failed to render pages: unexpected < in expression on line 1787 and column 113
    2: <p>var cx = &lsquo;015103900096539427448:ngwuia10qci&rsquo;;

Caused by the automatic iframe-resizer snippet. I assume this is a HUGO
BUG but I don't understand the rendering process.